### ISSUE TITLE
Fix System.ArgumentException in ImageService.SetTaskForTarget (FFImageLoading.Work.IImageLoaderTask currentTask)

### ISSUE THREAD

**Issue by agusibrahim** [agusibrahim/Aplikasi-PPOB-Xamarin#115]
### Stacktrace ###

FFImageLoading.ImageService.SetTaskForTarget (FFImageLoading.Work.IImageLoaderTask currentTask) [0x0006b] in <6da1e56736824600a2a4274fa130241a>:0;FFImageLoading

FFImageLoading.ImageServiceBase`1[TImageContainer].LoadImage (FFImageLoading.Work.IImageLoaderTask task) [0x00011] in <b97b20b56edf4a80bd2dfa12e27aaf18>:0;FFImageLoading

FFImageLoading.TaskParameterPlatformExtensions.Into[TImageView] (FFImageLoading.Work.TaskParameter parameters, FFImageLoading.Work.ITarget`2[TImageContainer,TImageView] target) [0x00034] in <6da1e56736824600a2a4274fa130241a>:0;FFImageLoading

FFImageLoading.TaskParameterPlatformExtensions.Into (FFImageLoading.Work.TaskParameter parameters, FFImageLoading.Views.ImageViewAsync imageView) [0x00007] in <6da1e56736824600a2a4274fa130241a>:0;FFImageLoading

FFImageLoading.Forms.Platform.CachedImageFastRenderer.UpdateBitmap (FFImageLoading.Forms.Platform.CachedImageView imageView, FFImageLoading.Forms.CachedImage image, FFImageLoading.Forms.CachedImage previousImage) [0x001e0] in <4ecfcdc3451f4124b3b366b6af3329f8>:0;FFImageLoading.Forms.Platform

FFImageLoading.Forms.Platform.CachedImageFastRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00121] in <4ecfcdc3451f4124b3b366b6af3329f8>:0;FFImageLoading.Forms.Platform

FFImageLoading.Forms.Platform.CachedImageFastRenderer.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x000c2] in <4ecfcdc3451f4124b3b366b6af3329f8>:0;FFImageLoading.Forms.Platform.CachedImageFastRenderer.Xamarin.Forms.Platform.Android

### Reason ###

System.ArgumentException

### Link to App Center ###

* [https://appcenter.ms/users/agusibrahim/apps/Retross-Android/crashes/errors/1613397548u](https://appcenter.ms/users/agusibrahim/apps/Retross-Android/crashes/errors/1613397548u)

**Comment by thisisthekap** [comment]
Getting the same issue on the following Android devices and OS Versions:

Device | OS Version
---|---
Mi A2 | 10
OnePlus 6 | 10
Galaxy S4 | 5.0.1

**Comment by thisisthekap** [comment]
@agusibrahim Was some fix made to mitigate this issue?

**Comment by sbs-Arockia-Jenitha** [comment]
Am also getting this issue. how to handle from your side?
